---
- name: Core
  community.general.homebrew:
    name: '{{ download_packages_base }}'
    state: present

- name: MacOS - Casks
  community.general.homebrew_cask:
    name: '{{ download_packages_homebrew_cask }}'
    state: present

- name: MacOS - Brew packages
  community.general.homebrew:
    name: '{{ download_packages_mac }}'
    state: present

- name: Install Cargo
  ansible.builtin.shell: |-
    set -o pipefail
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    creates: '{{ ansible_env.HOME }}/.cargo/'
