---
- name: Configure yabai
  when: ansible_facts['distribution'] == "MacOSX"
  block:
    # TODO replace with lineinfile
    - name: Configure Yabai
      ansible.builtin.shell: >
        echo "$(whoami) ALL=(root) NOPASSWD:
        sha256:$(shasum -a 256 $(which yabai))
        $(which yabai) --load-sa" > /private/etc/sudoers.d/yabai
      become: true
      args:
        creates: /private/etc/sudoers.d/yabai

    # - name: Configure Yabai
    #   lineinfile:
    #     path: /private/etc/sudoers.d/yabai
    #     line: "$(whoami) ALL=(root) NOPASSWD: $(which yabai) --load-sa"
    #   become: true

    - name: Start Yabai
      ansible.builtin.command: yabai --start-service
      register: yabai_start_result
      changed_when: yabai_start_result.rc != 0

    - name: Start Skhd
      ansible.builtin.command: skhd --start-service
      register: skhd_start_result
      changed_when: skhd_start_result.rc != 0
