---
- name: Inject Personal Github SSH key
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/id_home_github"
    block: |
      {{ home_github_ssh }}
    create: yes
    mode: "0700"
    state: present
    backup: true

- name: Inject Work Github SSH key
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/id_work_github"
    block: |
      {{ work_github_ssh }}
    create: yes
    mode: "0700"
    state: present
    backup: true

- name: Inject Azure VM SSH key
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/alberto01.pem"
    block: |
      {{ azure_vm_ssh }}
    create: yes
    mode: "0700"
    state: present
    backup: true

- name: Inject CinferenceCC VM SSH key
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/cinference-cc_key.pem"
    block: |
      {{ cinference_cc_ssh }}
    create: yes
    mode: "0700"
    state: present
    backup: true

- name: Inject OpenAI API key
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshenv"
    line: 'export OPENAI_API_KEY="{{ openai_api_key }}"'
    create: yes
    state: present
