---
- name: Ensure ~/.aws/ exists
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.aws'
    state: directory
    mode: '0755'
- name: Copy Config
  ansible.builtin.copy:
    dest: '{{ ansible_env.HOME }}/.aws/config'
    src: '{{ playbook_dir }}/roles/aws/config'
    mode: '0755'
- name: Copy Credentials
  ansible.builtin.copy:
    dest: '{{ ansible_env.HOME }}/.aws/credentials'
    src: '{{ playbook_dir }}/roles/aws/credentials'
    mode: '0755'
