"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$directory$git_branch$git_status$character"""
right_format="""$all"""
palette = "rose-pine"
command_timeout = 1000

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
vimcmd_symbol = '[V](bold green) '

[directory]
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format =  '[$symbol$branch ]($style)'
disabled = false
ignore_branches = ['master', 'main']

[git_status]
ignore_submodules = true

[golang]
disabled = false
style = 'bold blue'
symbol = " "

[python]
symbol = " "

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "gke_justwatch-compute_europe-west1-d_jw-k8s-prod-eu-2", style = "foam", context_alias = "prod"},
  { context_pattern = "gke_justwatch-compute_europe-west1-b_jw-k8s-stage-eu-2", style = "iris", context_alias = "stage"},
]
detect_files = ['k8s']

[docker_context]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true

[line_break]
disabled = true

[palettes.rose-pine]
base = '#191724'
surface = '#1f1d2e'
overlay = '#26233a'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#21202e'
highlight_med = '#403d52'
highlight_high = '#524f67'
