"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$directory$git_branch$git_status$character"""
right_format="""$all"""
palette = "rose-pine"
command_timeout = 1000

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
vimcmd_symbol = '[V](bold green) '

[directory]
style = 'foam'
read_only = " 󰌾"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
# symbol = " "
format =  '[$symbol$branch ]($style)'
disabled = false
ignore_branches = ['master', 'main']

[git_status]
ignore_submodules = true
style = 'rose'
stashed = '*${count}'
modified = '!${count}'
staged = '+${count}'
untracked = '?${count}'
deleted = '✘${count}'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'

[golang]
disabled = false
format = '[$symbol($version )]($style)'
style = 'bold blue'
symbol = " "
# symbol = "󰟓 "

[python]
symbol = " "
style = "gold bold"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[kubernetes]
symbol = '󱃾 '
disabled = false
format = '[$symbol$context( \($namespace\))](bold $style) '
contexts = [
  { context_pattern = "gke_justwatch-compute_europe-west1-d_jw-k8s-prod-eu-2", style = "foam", context_alias = "prod"},
  { context_pattern = "gke_justwatch-compute_europe-west1-b_jw-k8s-stage-eu-2", style = "iris", context_alias = "stage"},
]
detect_files = ['k8s']

[terraform]
disabled = true

[buf]
disabled = true

[docker_context]
disabled = true
symbol = " "

[gcloud]
symbol = "󱇶 "
disabled = true

[aws]
symbol = "  "
disabled = true

[time]
disabled = false
format = '[$time]($style) '
style = 'subtle'

[line_break]
disabled = true

[nodejs]
style = "green"
format = '[$symbol$version](green) '

[package]
symbol = "󰏗 "
format = '[$symbol$version](208 bold) '

[palettes.rose-pine]
base = '#191724'
surface = '#1f1d2e'
overlay = '#26233a'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#21202e'
highlight_med = '#403d52'
highlight_high = '#524f67'
