---
- name: Bootstrap Linux
  hosts: localhost
  vars_files:
    - vars/packages.yaml
  roles:
    - sync_keys
    - configs

  tasks:
    - name: Install packages
      become: true
      package:
        name: "{{ base_packages + linux_packages}}"
        state: present
