---
- name: Bootstrap Mac
  hosts: localhost
  gather_facts: false
  collections:
    - community.general
  vars_files:
    - vars/packages.yaml
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install Homebrew
      shell: |
        "/bin/bash -c \
        '$(curl -fsSL \
        https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)'"
      args:
        creates: /opt/homebrew/bin/brew

    - name: Check if community.general collection is installed
      command: ansible-galaxy collection list
      register: collection_list_result
      changed_when: false

    - name: Install community.general collection
      shell: ansible-galaxy collection install community.general
      when: |
        "'community.general' not in \
        collection_list_result.stdout_lines | join(' ')"

    - name: Install brew packages
      with_items:
        - "{{ base_packages }}"
        - "{{ mac_packages }}"
      homebrew:
        name: "{{ item }}"
        state: present
        update_homebrew: true
        upgrade_all: true

    - name: Configure Yabai
      shell: >
        echo "$(whoami) ALL=(root) NOPASSWD: \
        sha256:$(shasum -a 256 $(which yabai)) $(which yabai) --load-sa" > \
        /private/etc/sudoers.d/yabai
      become: true
      args:
        creates: /private/etc/sudoers.d/yabai

    - name: Start Yabai
      command: yabai --start-service
      register: yabai_start_result
      changed_when: yabai_start_result.rc != 0

    - name: Start Skhd
      command: skhd --start-service
      register: skhd_start_result
      changed_when: skhd_start_result.rc != 0
