---
download_packages_base:
  - fzf
  - bat
  - neovim
  - eza
  - glow
  - jq
  - yq
  - nodejs
  - pyenv
  - ripgrep
  - tmux
  - stow
  - tree
  - go
  - wget
  - zsh
  - kubectl
  - kubectx
  - shellcheck
  - gum
  - starship
  - lazygit
  - btop

download_packages_homebrew_cask:
  - silicon
  - spotify
  - font-jetbrains-mono-nerd-font
  # - ghostty
  - zen-browser

download_packages_mac:
  # - raycast
  # - whatsapp
  - awscli
  - ansible-lint
  # - gh
  - golangci-lint
  # - nerdfetch
  # - colima
