---
name: Linting
on:
  pull_request:
    paths:
      - '**/*.nix'
  push:
    paths:
      - '**/*.nix'
    branches:
      - main
  workflow_dispatch:
jobs:
  nix-lint:
    name: Nix Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Check formatting (nixfmt)
        run: nix run nixpkgs#nixfmt -- --check $(find . -name '*.nix')

      - name: Run statix
        run: nix run nixpkgs#statix -- check .

      - name: Run deadnix
        run: nix run nixpkgs#deadnix -- .
